---
title: "telemetry"
author: "Philip Dixon and Gang Han"
date: "4/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code to recreate analyses in Fisher et al 2020

```{r libraries, include=FALSE}
library(readxl)
library(ANOVAreplication)
library(tidyr)
library(dplyr)
library(magrittr)
library(plotrix)
library(lme4)
library(bbmle)
library(truncnorm)
library(lattice)
library(ellipse)
library(lubridate)
library(mgcv)
```

Define multiple functions used in the code
```{r functions}
source('functions.r')
source('find functions.r')
```

### Stationary locations: 
```{r read stationary}
df.all <- read.csv('BGE070718.csv', as.is=T)
# raw data from automated receivers, with location information added
```

```{r predict stationary, cache=TRUE}
source('BGE prediction.r')
```

```{r plot stationary}
source('BGE plot.r')
```

### Moving target
```{r read and calibrate for walk}
source('walk calibrate.r')
```

```{r predict walk, cache=TRUE}
source('walk predict.r')
```

```{r plot walk}
source('walk plot.r')
```

### Transmitter on a flying butterfly
```{r calibrate Monarch 171}
source('M171 calibrate.r')
```

```{r predict Monarch 171, cache=TRUE}
source('M171 predict.r')
```

```{r plot Monarch 171}
source('M171 plot.r')
```

